In [1]:
import numpy as np
import pandas as pd

In [18]:
df= pd.read_csv("weather.csv")

In [19]:
df.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 22 columns):
MinTemp          366 non-null float64
MaxTemp          366 non-null float64
Rainfall         366 non-null float64
Evaporation      366 non-null float64
Sunshine         363 non-null float64
WindGustDir      363 non-null object
WindGustSpeed    364 non-null float64
WindDir9am       335 non-null object
WindDir3pm       365 non-null object
WindSpeed9am     359 non-null float64
WindSpeed3pm     366 non-null int64
Humidity9am      366 non-null int64
Humidity3pm      366 non-null int64
Pressure9am      366 non-null float64
Pressure3pm      366 non-null float64
Cloud9am         366 non-null int64
Cloud3pm         366 non-null int64
Temp9am          366 non-null float64
Temp3pm          366 non-null float64
RainToday        366 non-null object
RISK_MM          366 non-null float64
RainTomorrow     366 non-null object
dtypes: float64(12), int64(5), object(5)
memory usage: 63.0+ KB

In [21]:
temp_df=df

In [89]:
li=[]
sum=0
for i, value in enumerate(temp_df["MinTemp"]):
    
    if value == 12:
        li.append(i)
        sum=sum+1
for ele in li:
    print(pd.DataFrame(temp_df.loc[[ele]]))
print("the count is ",sum)

    MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
23     12.0     24.3       0.4          1.2       7.5         NNE

    WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
23           26.0        WSW         NE           6.0  ...           57

    Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
23       1020.7       1019.2         7         5     17.8     22.8         No

    RISK_MM RainTomorrow
23      0.0           No

[1 rows x 22 columns]
     MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
111     12.0     28.9       0.0          7.2       8.2         ESE

     WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
111           39.0        SSE        WNW           2.0  ...           31

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
111       1012.2       1009.1         2         7     17.4     28.6

     RainToday  RISK_MM RainTomorrow
111         No      1.8          Yes

[1 rows x 22 columns]
     MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
115     12.0     23.8       0.0         10.4      12.4          NW

     WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
115           44.0         NW        WNW          15.0  ...           34

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
115       1007.9       1007.2         0         1     15.1     22.9

     RainToday  RISK_MM RainTomorrow
115         No      0.0           No

[1 rows x 22 columns]
     MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
125     12.0     27.6       0.0          6.0      11.0           E

     WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
125           46.0        SSE        WSW           7.0  ...           35

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
125       1025.5       1022.2         1         1     15.7     26.2

     RainToday  RISK_MM RainTomorrow
125         No      0.0           No

[1 rows x 22 columns]
the count is  4